var temples = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "label": "Temple - Amphipolis", "deities": ["Isis"], "centuries": ["4 BCE", "3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 23.847445, 40.820354 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Antiochia ad Orontem", "deities": ["Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 36.165318, 36.200663 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Argos", "deities": ["Isis", "Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 22.719464, 37.631561 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Aspendus\/Aspendos", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 31.171507, 36.9392952 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Astipalaia", "deities": ["Sarapis", "Isis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 26.35142, 36.547366 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Athenae", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 23.7239852, 37.9727465 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Bargylia", "deities": ["Sarapis" ,"Anubis", "Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.589505, 37.195835 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Camirus\/Kamiros", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.921195, 36.336185 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Carthago", "deities": ["Isis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 10.3272205, 36.8538753 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Ceramus\/Keramos", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.9562175, 37.041728 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Chaironeia\/Chaeorena", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 22.841628, 38.494419 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Chalcis", "deities": ["Sarapis", "Isis", "Anubis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 23.621937, 38.457139 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Chios", "deities": ["Sarapis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 26.053, 38.414 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Cyrene", "deities": ["Isis"], "centuries": ["4 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 21.856333, 32.8218757 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Delos A", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 25.271111, 37.393333 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Ephesus", "deities": ["Isis", "Sarapis", "Anubis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.3455126, 37.9421834 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Eretria", "deities": ["Isis"], "centuries": ["4 BCE", "3 BCE", "2 BCE", "1 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 23.790535, 38.398169 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Gonnos", "deities": ["Sarapis", "Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 22.498138, 39.858934 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Gortyn", "deities": ["Isis", "Sarapis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 24.9469437, 35.0627202 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Halicarnassus", "deities": ["Isis", "Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.423765, 37.0382205 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Hyrcania", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 55.3615934, 37.103114 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Lindus\/Lindos", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE", "1 BCE", "1 CE", "2 CE"] }, "geometry": { "type": "Point", "coordinates": [ 28.0881777, 36.0913239 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Magnesia ad Maeandrum", "deities": ["Sarapis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.526039, 37.8505485 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Minoa", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 25.8640625, 36.8241875 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Orchomenus", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE", "1 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 22.974702, 38.493319 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Paros", "deities": ["Sarapis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 25.19, 37.05 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Phoenix", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 28.11667, 36.63333 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Piraeus", "deities": ["Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 23.644609, 37.937222 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Priene", "deities": ["Sarapis", "Isis", "Apis"], "centuries": [] }, "geometry": { "type": "Point", "coordinates": [ 27.2980995, 37.6599361 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Rhamnous", "deities": ["Sarapis", "Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 24.028009, 38.222727 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Rhodos (city)", "deities": [], "centuries": ["2 BCE", "1 BCE", "1 CE", "2 CE"] }, "geometry": { "type": "Point", "coordinates": [ 28.21672, 36.440683 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Samos", "deities": ["Isis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 26.944483, 37.68825 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Stratonicea", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 28.0645, 37.31359 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Syme", "deities": ["Sarapis"], "centuries": ["2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 27.813674, 36.566308 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Tauromenium", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 15.292111, 37.852313 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Thera", "deities": ["Isis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 25.433333, 36.416667 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Thessalonica", "deities": ["Sarapis"], "centuries": ["3 BCE", "2 BCE", "1 BCE", "1 CE", "2 CE", "3 CE", "4 CE"] }, "geometry": { "type": "Point", "coordinates": [ 22.949569, 40.630282 ] } },
{ "type": "Feature", "properties": { "label": "Temple - Tyrus", "deities": ["Sarapis"], "centuries": ["3 BCE"] }, "geometry": { "type": "Point", "coordinates": [ 35.209358, 33.268071 ] } }
]
}
